$ErrorActionPreference = 'Stop'

# Reads the top "## X.Y.Z" entry from CHANGELOG.md and writes
# src/AssemblyVersion.cs so Application.ProductVersion matches the released
# version. Called by build-release.ps1 and run-tests.ps1 before csc.
# The generated file is .gitignored.

$Root = Split-Path -Parent $PSScriptRoot
$Changelog = Get-Content -Raw -Path (Join-Path $Root 'CHANGELOG.md')
$Match = [regex]::Match($Changelog, '(?m)^##\s+(?<version>\d+\.\d+\.\d+)\s*$')
if (!$Match.Success) { throw 'Could not find a version header (## X.Y.Z) in CHANGELOG.md' }
$Version = $Match.Groups['version'].Value
$AssemblyVersion = "$Version.0"

$OutPath = Join-Path $Root 'src\AssemblyVersion.cs'
$Body = @"
// Generated by scripts/generate-version.ps1 from CHANGELOG.md. Do not edit by
// hand; the file is gitignored and overwritten before every csc invocation.

using System.Reflection;

[assembly: AssemblyVersion("$AssemblyVersion")]
[assembly: AssemblyFileVersion("$AssemblyVersion")]
[assembly: AssemblyInformationalVersion("$Version")]
"@

Set-Content -Path $OutPath -Value $Body -Encoding utf8
